### ISSUE TITLE
cdn.jsdelivr.net链接中的github_username/repo_name@tag_version/path/to/file 怎么自定义

### ISSUE THREAD

**Issue by nondevops** [zqhong/jsdelivr-cdn#2]
cdn.jsdelivr.net链接中的github_username/repo_name@tag_version/path/to/file 怎么自定义

**Comment by zqhong** [comment]
将需要 CDN 加速的文件上传到你自己的 GitHub 仓库就行。

这里有说明，下拉到 GitHub CDN 章节：
https://www.jsdelivr.com/features

我备注中并不准确，官方的定义是这样的：
```
Load any GitHub release, commit, or branch:

https://cdn.jsdelivr.net/gh/user/repo@version/file
```
